services:
  webserver:
    image: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - app:/var/www/html

  database:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - my:/var/lib/mysql

  webproxy:
    image: caio86/asa-projeto-02-webproxy
    ports:
      - 8080:8080

volumes:
  app:
  my:

networks:
  default:
    name: wordpress
